### ISSUE TITLE
Getting Error from time to time

### ISSUE THREAD

**Issue by MasterEnderman** [BuiltBrokenModding/SBM-BashFireMakeRock#5]
https://i.imgur.com/b8VFGol.jpg

sometimes it just throw this error when a player starts breaking a block with his hand and you remove the cursor from the block you started mining.

**Comment by bl4ckscor3** [comment]
Please reproduce the error and post your `latest.log` file using https://pastebin.com.

**Comment by DarkGuardsman** [comment]
Wasn't this fixed in the latest version?

**Comment by Tommeh1** [comment]
From what i have seen on the test server that was indeed fixed in the latest version.

**Comment by MasterEnderman** [comment]
```
[10:02:46] [Server thread/ERROR] [bashfiremakerock]: Unexpected error while handling click event for '4ozscoop [acc176e5-eadf-4f6c-8d6b-c4aa2caca52c] created fire at BlockPos{x=2, y=78, z=3} in world divine 2 dim: 0'
java.lang.NullPointerException: null
	at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:40) ~[bhc.class:?]
	at net.minecraft.util.math.RayTraceResult.<init>(RayTraceResult.java:22) ~[bhc.class:?]
	at com.builtbroken.bashrockmakefire.logic.EventHandler.onBlockPunch(EventHandler.java:36) [EventHandler.class:1.12.2-1.0.0b20190310153703]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_299_EventHandler_onBlockPunch_LeftClickBlock.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130) [ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:141) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:693) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[10:02:46] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] bashfiremakerock:error.event.click
```

**Comment by DarkGuardsman** [comment]
We don't even have a raytrace in the latest version. Update to the latest
